apiVersion: apps/v1
kind: Deployment
metadata:
  name: <<replace_container_name>>
spec:
  replicas: 1
  selector:
    matchLabels:
      app: <<replace_container_name>>
  template:
    metadata:
      labels:
        app: <<replace_container_name>>     
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - image: <<acr_name>>.azurecr.io/<<replace_container_name>>
        name: <<replace_container_name>>
        env:
          - name: ASPNETCORE_ENVIRONMENT
            value: Development
          - name: ASPNETCORE_URLS
            value: "http://+:80"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: <<replace_container_name>>
spec:
  # LoadBalancer is for demo purposes only
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector:
    app: <<replace_container_name>>
